### ISSUE TITLE
`Ingress::read_from` causes busy-loop if write_buf is full

### ISSUE THREAD

**Issue by t-moe** [FactbirdHQ/atat#211]
The current implementation of `Ingress::read_from` can cause the MCU to busy-loop: If for some reason the write_buf becomes full, the embedded_io_async::Read will return/error immediately, causing the MCU to busy-loop.

https://github.com/FactbirdHQ/atat/blob/2768e5ae760992641defc048972c2aa7e12043d2/atat/src/ingress.rs#L57-L74

As to why the write_buf became full in my case, I'm still investigating.

(CC @cacharle)

**Comment by MathiasKoch** [comment]
Nice catch

**Comment by t-moe** [comment]
Am I correct that ATAT should in theory be able to recover from garbage data at the beginning of the buffer?
If so, we could just print a warning and self.clear() if buf.len()==0

**Comment by MathiasKoch** [comment]
I would say so yeah.

I have been meaning to set up a fuzz test on it, to verify this behaviour.
